Add files via upload
First run — recording until next half-hour or hour.
Traceback (most recent call last):
  File "/home/rathkopf/UrchinCam/urchincam_segment_video.py", line 62, in <module>
    continuous_half_hour_segments()
  File "/home/rathkopf/UrchinCam/urchincam_segment_video.py", line 50, in continuous_half_hour_segments
    start_camera_recording(duration)
  File "/home/rathkopf/UrchinCam/urchincam_segment_video.py", line 7, in start_camera_recording
    current_time = datetime.now().strftime()
TypeError: strftime() missing required argument 'format' (pos 1)